# generated by Claude

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.path import Path
from matplotlib.patches import PathPatch
import matplotlib.colors as mcolors
from scipy.interpolate import interp1d

def disk_to_cie_xy(r, theta):
    """
    Map a point in the unit disk (r, theta) to the CIE 1931 xy chromaticity diagram.
    
    Parameters:
    r (float): Radius in the unit disk (0 to 1)
    theta (float): Angle in radians (0 to 2π)
    
    Returns:
    tuple: (x, y) coordinates in the CIE 1931 xy chromaticity diagram
    """
    # Define the spectral locus points (simplified approximation)
    # These are approximate points along the horseshoe curve of the CIE 1931 diagram
    # Wavelengths from 380nm to 700nm (violet to red)
    spectral_locus = np.array([
        # x, y coordinates for wavelengths
        [0.1741, 0.0050],  # 380nm (violet)
        [0.1740, 0.0050],  # 385nm
        [0.1738, 0.0049],  # 390nm
        [0.1736, 0.0049],  # 395nm
        [0.1733, 0.0048],  # 400nm
        [0.1730, 0.0048],  # 405nm
        [0.1726, 0.0048],  # 410nm
        [0.1721, 0.0048],  # 415nm
        [0.1714, 0.0051],  # 420nm
        [0.1703, 0.0058],  # 425nm
        [0.1689, 0.0069],  # 430nm
        [0.1669, 0.0086],  # 435nm
        [0.1644, 0.0109],  # 440nm
        [0.1611, 0.0138],  # 445nm
        [0.1566, 0.0177],  # 450nm
        [0.1510, 0.0227],  # 455nm
        [0.1440, 0.0297],  # 460nm
        [0.1355, 0.0399],  # 465nm
        [0.1241, 0.0578],  # 470nm
        [0.1096, 0.0868],  # 475nm
        [0.0913, 0.1327],  # 480nm
        [0.0687, 0.2007],  # 485nm
        [0.0454, 0.2950],  # 490nm
        [0.0235, 0.4127],  # 495nm
        [0.0082, 0.5384],  # 500nm
        [0.0039, 0.6548],  # 505nm
        [0.0139, 0.7502],  # 510nm
        [0.0389, 0.8120],  # 515nm
        [0.0743, 0.8338],  # 520nm
        [0.1142, 0.8262],  # 525nm
        [0.1547, 0.8059],  # 530nm
        [0.1929, 0.7816],  # 535nm
        [0.2296, 0.7543],  # 540nm
        [0.2658, 0.7243],  # 545nm
        [0.3016, 0.6923],  # 550nm
        [0.3373, 0.6589],  # 555nm
        [0.3731, 0.6245],  # 560nm
        [0.4087, 0.5896],  # 565nm
        [0.4441, 0.5547],  # 570nm
        [0.4788, 0.5202],  # 575nm
        [0.5125, 0.4866],  # 580nm
        [0.5448, 0.4544],  # 585nm
        [0.5752, 0.4242],  # 590nm
        [0.6029, 0.3965],  # 595nm
        [0.6270, 0.3725],  # 600nm
        [0.6482, 0.3514],  # 605nm
        [0.6658, 0.3340],  # 610nm
        [0.6801, 0.3197],  # 615nm
        [0.6915, 0.3083],  # 620nm
        [0.7006, 0.2993],  # 625nm
        [0.7079, 0.2920],  # 630nm
        [0.7140, 0.2859],  # 635nm
        [0.7190, 0.2809],  # 640nm
        [0.7230, 0.2770],  # 645nm
        [0.7260, 0.2740],  # 650nm
        [0.7283, 0.2717],  # 655nm
        [0.7300, 0.2700],  # 660nm
        [0.7311, 0.2689],  # 665nm
        [0.7320, 0.2680],  # 670nm
        [0.7327, 0.2673],  # 675nm
        [0.7334, 0.2666],  # 680nm
        [0.7340, 0.2660],  # 685nm
        [0.7344, 0.2656],  # 690nm
        [0.7346, 0.2654],  # 695nm
        [0.7347, 0.2653],  # 700nm
    ])
    
    # Close the curve with the line of purples
    purple_line = np.array([
        [0.7347, 0.2653],  # 700nm
        [0.1741, 0.0050]   # 380nm
    ])
    
    # Define the white point (D65)
    white_point = np.array([0.3127, 0.3290])
    
    # Parameterize the spectral locus for interpolation
    num_points = len(spectral_locus)
    t = np.linspace(0, 1, num_points)
    
    # Create interpolation functions for the spectral locus
    fx = interp1d(t, spectral_locus[:, 0], kind='cubic')
    fy = interp1d(t, spectral_locus[:, 1], kind='cubic')
    
    # Map theta to the parameter t
    # Adjust to map θ=0 to red (700nm, t≈1) and proceed counterclockwise
    t_theta = (1 - (theta / (2 * np.pi))) % 1
    
    # Get the point on the spectral locus
    if t_theta <= 1 and t_theta >= 0:
        locus_x = fx(t_theta)
        locus_y = fy(t_theta)
    else:
        # For the purple line (this is a simplification)
        purple_t = (t_theta - 1) / 0.05  # Scale to [0,1] for the purple line
        locus_x = purple_line[0, 0] * (1 - purple_t) + purple_line[1, 0] * purple_t
        locus_y = purple_line[0, 1] * (1 - purple_t) + purple_line[1, 1] * purple_t
    
    # Interpolate between white point and spectral locus based on radius
    x = white_point[0] * (1 - r) + locus_x * r
    y = white_point[1] * (1 - r) + locus_y * r
    
    return x, y

def plot_disk_to_cie_mapping(num_points=20):
    """
    Visualize the mapping from a unit disk to the CIE 1931 xy chromaticity diagram.
    
    Parameters:
    num_points (int): Number of points to sample along each dimension
    """
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 8))
    
    # Plot the unit disk
    ax1.set_aspect('equal')
    ax1.set_xlim(-1.2, 1.2)
    ax1.set_ylim(-1.2, 1.2)
    ax1.add_patch(plt.Circle((0, 0), 1, fill=False, color='black'))
    ax1.axhline(y=0, color='gray', linestyle='--', alpha=0.5)
    ax1.axvline(x=0, color='gray', linestyle='--', alpha=0.5)
    ax1.set_title('Unit Disk')
    ax1.set_xlabel('x')
    ax1.set_ylabel('y')
    
    # Plot the CIE 1931 chromaticity diagram
    ax2.set_aspect('equal')
    ax2.set_xlim(-0.1, 0.9)
    ax2.set_ylim(-0.1, 0.9)
    
    # Define the spectral locus points (same as in the function)
    spectral_locus = np.array([
        [0.1741, 0.0050],  # 380nm (violet)
        [0.1740, 0.0050],  # 385nm
        [0.1738, 0.0049],  # 390nm
        [0.1736, 0.0049],  # 395nm
        [0.1733, 0.0048],  # 400nm
        [0.1730, 0.0048],  # 405nm
        [0.1726, 0.0048],  # 410nm
        [0.1721, 0.0048],  # 415nm
        [0.1714, 0.0051],  # 420nm
        [0.1703, 0.0058],  # 425nm
        [0.1689, 0.0069],  # 430nm
        [0.1669, 0.0086],  # 435nm
        [0.1644, 0.0109],  # 440nm
        [0.1611, 0.0138],  # 445nm
        [0.1566, 0.0177],  # 450nm
        [0.1510, 0.0227],  # 455nm
        [0.1440, 0.0297],  # 460nm
        [0.1355, 0.0399],  # 465nm
        [0.1241, 0.0578],  # 470nm
        [0.1096, 0.0868],  # 475nm
        [0.0913, 0.1327],  # 480nm
        [0.0687, 0.2007],  # 485nm
        [0.0454, 0.2950],  # 490nm
        [0.0235, 0.4127],  # 495nm
        [0.0082, 0.5384],  # 500nm
        [0.0039, 0.6548],  # 505nm
        [0.0139, 0.7502],  # 510nm
        [0.0389, 0.8120],  # 515nm
        [0.0743, 0.8338],  # 520nm
        [0.1142, 0.8262],  # 525nm
        [0.1547, 0.8059],  # 530nm
        [0.1929, 0.7816],  # 535nm
        [0.2296, 0.7543],  # 540nm
        [0.2658, 0.7243],  # 545nm
        [0.3016, 0.6923],  # 550nm
        [0.3373, 0.6589],  # 555nm
        [0.3731, 0.6245],  # 560nm
        [0.4087, 0.5896],  # 565nm
        [0.4441, 0.5547],  # 570nm
        [0.4788, 0.5202],  # 575nm
        [0.5125, 0.4866],  # 580nm
        [0.5448, 0.4544],  # 585nm
        [0.5752, 0.4242],  # 590nm
        [0.6029, 0.3965],  # 595nm
        [0.6270, 0.3725],  # 600nm
        [0.6482, 0.3514],  # 605nm
        [0.6658, 0.3340],  # 610nm
        [0.6801, 0.3197],  # 615nm
        [0.6915, 0.3083],  # 620nm
        [0.7006, 0.2993],  # 625nm
        [0.7079, 0.2920],  # 630nm
        [0.7140, 0.2859],  # 635nm
        [0.7190, 0.2809],  # 640nm
        [0.7230, 0.2770],  # 645nm
        [0.7260, 0.2740],  # 650nm
        [0.7283, 0.2717],  # 655nm
        [0.7300, 0.2700],  # 660nm
        [0.7311, 0.2689],  # 665nm
        [0.7320, 0.2680],  # 670nm
        [0.7327, 0.2673],  # 675nm
        [0.7334, 0.2666],  # 680nm
        [0.7340, 0.2660],  # 685nm
        [0.7344, 0.2656],  # 690nm
        [0.7346, 0.2654],  # 695nm
        [0.7347, 0.2653],  # 700nm
    ])
    
    # Connect back to the starting point (Line of Purples)
    spectral_locus_closed = np.vstack([spectral_locus, spectral_locus[0]])
    
    # Plot the CIE diagram boundary
    ax2.plot(spectral_locus_closed[:, 0], spectral_locus_closed[:, 1], 'k-')
    
    # Define the white point (D65)
    white_point = np.array([0.3127, 0.3290])
    ax2.plot(white_point[0], white_point[1], 'ko', markersize=6)
    ax2.annotate('D65', xy=white_point + np.array([0.01, 0.01]))
    
    # Plot wavelength markers
    wavelengths = [380, 460, 480, 520, 540, 580, 600, 700]
    indices = [0, 16, 20, 28, 32, 40, 44, 64]  # Corresponding indices in spectral_locus
    for i, wl in zip(indices, wavelengths):
        ax2.annotate(f"{wl}nm", xy=(spectral_locus[i, 0], spectral_locus[i, 1]),
                   xytext=(spectral_locus[i, 0] + 0.02, spectral_locus[i, 1] + 0.02),
                   fontsize=8)
    
    ax2.set_title('CIE 1931 xy Chromaticity Diagram')
    ax2.set_xlabel('x')
    ax2.set_ylabel('y')
    
    # Sample points from the unit disk and map them to CIE space
    radii = np.linspace(0, 1, num_points)
    thetas = np.linspace(0, 2 * np.pi, num_points, endpoint=False)
    
    # Create a grid of radii and angles
    r_grid, theta_grid = np.meshgrid(radii, thetas)
    
    # Map each point to the CIE diagram
    disk_points = []
    cie_points = []
    
    for i in range(num_points):
        for j in range(num_points):
            r = r_grid[i, j]
            theta = theta_grid[i, j]
            
            # Disk coordinates
            x_disk = r * np.cos(theta)
            y_disk = r * np.sin(theta)
            disk_points.append((x_disk, y_disk))
            
            # CIE coordinates
            x_cie, y_cie = disk_to_cie_xy(r, theta)
            cie_points.append((x_cie, y_cie))
            
            # Plot selected points with connections
            if (i % 4 == 0 and j % 4 == 0) or (r > 0.9 and i % 2 == 0):
                ax1.plot(x_disk, y_disk, 'o', markersize=4, 
                         color=plt.cm.hsv(theta/(2*np.pi)))
                ax2.plot(x_cie, y_cie, 'o', markersize=4, 
                         color=plt.cm.hsv(theta/(2*np.pi)))
    
    # Plot polar coordinate grid lines in the disk
    for r in [0.25, 0.5, 0.75]:
        circle = plt.Circle((0, 0), r, fill=False, linestyle='--', color='gray', alpha=0.5)
        ax1.add_patch(circle)
    
    for theta in np.linspace(0, 2*np.pi, 12, endpoint=False):
        x = np.cos(theta)
        y = np.sin(theta)
        ax1.plot([0, x], [0, y], 'gray', linestyle='--', alpha=0.5)
    
    # Add a title and adjust layout
    plt.suptitle('Mapping from Unit Disk to CIE 1931 xy Chromaticity Diagram', fontsize=16)
    plt.tight_layout()
    
    return fig

def generate_color_patch_from_xy(x, y):
    """
    Generate an approximate RGB color from CIE xy coordinates.
    This is a simplification and not colorimetrically accurate.
    
    Parameters:
    x, y (float): CIE xy coordinates
    
    Returns:
    tuple: RGB color tuple
    """
    # Convert xy to XYZ
    Y = 1.0  # Assume Y=1 for simplicity
    X = (Y / y) * x
    Z = (Y / y) * (1 - x - y)
    
    # XYZ to RGB conversion matrix (sRGB D65)
    # This is a simplified conversion matrix
    M = np.array([
        [3.2406, -1.5372, -0.4986],
        [-0.9689, 1.8758, 0.0415],
        [0.0557, -0.2040, 1.0570]
    ])
    
    # Convert to linear RGB
    rgb_linear = np.dot(M, np.array([X, Y, Z]))
    
    # Apply gamma correction
    rgb = np.zeros_like(rgb_linear)
    for i in range(3):
        if rgb_linear[i] <= 0.0031308:
            rgb[i] = 12.92 * rgb_linear[i]
        else:
            rgb[i] = 1.055 * (rgb_linear[i] ** (1/2.4)) - 0.055
    
    # Clip values to [0, 1]
    rgb = np.clip(rgb, 0, 1)
    
    return tuple(rgb)

def plot_interactive_disk_mapping():
    """
    Create an interactive plot showing color samples mapped from disk to CIE space
    """
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 8))
    
    # Setup the unit disk plot
    ax1.set_aspect('equal')
    ax1.set_xlim(-1.2, 1.2)
    ax1.set_ylim(-1.2, 1.2)
    ax1.add_patch(plt.Circle((0, 0), 1, fill=False, color='black'))
    ax1.axhline(y=0, color='gray', linestyle='--', alpha=0.5)
    ax1.axvline(x=0, color='gray', linestyle='--', alpha=0.5)
    ax1.set_title('Unit Disk')
    ax1.set_xlabel('x')
    ax1.set_ylabel('y')
    
    # Setup the CIE diagram plot
    ax2.set_aspect('equal')
    ax2.set_xlim(-0.1, 0.9)
    ax2.set_ylim(-0.1, 0.9)
    
    # Define the spectral locus points (same as before)
    spectral_locus = np.array([
        # Same data as before
        [0.1741, 0.0050],  # 380nm (violet)
        # ... other points would be here
        [0.7347, 0.2653],  # 700nm
    ])
    
    # Connect back to the starting point (Line of Purples)
    spectral_locus_closed = np.vstack([spectral_locus, spectral_locus[0]])
    
    # Plot the CIE diagram boundary
    ax2.plot(spectral_locus_closed[:, 0], spectral_locus_closed[:, 1], 'k-')
    
    # Define the white point (D65)
    white_point = np.array([0.3127, 0.3290])
    ax2.plot(white_point[0], white_point[1], 'ko', markersize=6)
    ax2.annotate('D65', xy=white_point + np.array([0.01, 0.01]))
    
    ax2.set_title('CIE 1931 xy Chromaticity Diagram')
    ax2.set_xlabel('x')
    ax2.set_ylabel('y')
    
    # Create a 2D grid of samples for visualization
    grid_size = 30
    r_values = np.linspace(0, 1, grid_size)
    theta_values = np.linspace(0, 2*np.pi, grid_size, endpoint=False)
    
    # Create a color visualization
    for r_idx, r in enumerate(r_values):
        for theta_idx, theta in enumerate(theta_values):
            # Disk coordinates
            x_disk = r * np.cos(theta)
            y_disk = r * np.sin(theta)
            
            # Map to CIE coordinates
            x_cie, y_cie = disk_to_cie_xy(r, theta)
            
            # Try to approximate the color (this is simplified)
            try:
                color = generate_color_patch_from_xy(x_cie, y_cie)
                
                # Draw color patches
                disk_patch = plt.Rectangle(
                    (x_disk-0.04, y_disk-0.04), 0.08, 0.08, 
                    color=color, alpha=0.7
                )
                ax1.add_patch(disk_patch)
                
                # Only plot some points in CIE space to avoid crowding
                if r_idx % 3 == 0 and theta_idx % 3 == 0:
                    cie_patch = plt.Rectangle(
                        (x_cie-0.01, y_cie-0.01), 0.02, 0.02, 
                        color=color, alpha=0.7
                    )
                    ax2.add_patch(cie_patch)
            except:
                # Skip invalid colors
                pass
    
    plt.suptitle('Color Mapping from Unit Disk to CIE 1931 xy Chromaticity Diagram', fontsize=16)
    plt.tight_layout()
    
    return fig

# Example usage
if __name__ == "__main__":
    # Plot the basic mapping
    fig1 = plot_disk_to_cie_mapping(20)
    # plt.savefig('disk_to_cie_mapping.png', dpi=300)
    
    # Plot the interactive color map
    fig2 = plot_interactive_disk_mapping()
    # plt.savefig('disk_to_cie_color_mapping.png', dpi=300)
    
    plt.show()

# To use the mapping function directly:
# x, y = disk_to_cie_xy(0.8, np.pi/4)  # Maps a point at r=0.8, θ=π/4 to CIE xy space
